/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_AUDIO_FILES           3
#define MMAP_AUDIO_CHECKSUM        0xC354

enum MMAP_AUDIO_LISTS {
    MMAP_AUDIO_ECHO_WAV = 0,        /*!< echo.wav */
    MMAP_AUDIO_ECHO1_WAV = 1,        /*!< echo1.wav */
    MMAP_AUDIO_MUYU_WAV = 2,        /*!< muyu.wav */
};
