// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "esp_err.h"
#include "esp_check.h"
#include "ui.h"
#include "esp_log.h"
#include "ui_helpers.h"
#include "bsp/esp-bsp.h"
#include "tinyGL_cube.h"
#include "lv_lottie.h"
#include "lv_100ask_2048.h"

#include "esp_camera.h"
#include "thorvg_capi.h"
#include "app_audio_record.h"
#include "mmap_generate_lottie_assets.h"

#define TAG "ui"

#define LOTTIE_SIZE_HOR         (180)
#define LOTTIE_SIZE_VER         (180)
#define ESP_SPARKBOT_URL        "https://lvgl.io"
#define GONGDE_THRESHOLD        20
#define FISH_X_START            -(240 + LOTTIE_SIZE_HOR) / 2
#define FISH_X_END              (240 + LOTTIE_SIZE_HOR) / 2

extern mmap_assets_handle_t asset_lottie;

static lv_timer_t *timer_camera = NULL;
static lv_timer_t *timer_fish = NULL;

///////////////////// VARIABLES ////////////////////
void muyushow_Animation(lv_obj_t *TargetObject, int delay);
void blink_Animation(lv_obj_t *TargetObject, int delay);
void falldown_Animation(lv_obj_t *TargetObject, int delay);
void weather_Animation(lv_obj_t *TargetObject, int delay);
void riseup_Animation(lv_obj_t *TargetObject, int delay);
void opaon_Animation(lv_obj_t *TargetObject, int delay);
void gonde_txt_Animation(lv_obj_t *TargetObject, int delay);

// 音乐播放器变量定义
lv_obj_t *ui_music_player = NULL;
lv_obj_t *ui_panel_music = NULL;
lv_obj_t *ui_music_title = NULL;
lv_obj_t *ui_music_play_btn = NULL;
lv_obj_t *ui_music_progress = NULL;

// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t *e);
lv_obj_t *ui_home;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_hour;
lv_obj_t *ui_min;
lv_obj_t *ui_date;
lv_obj_t *ui_weekday;
lv_obj_t *ui_temp;
lv_obj_t *ui_weather;
lv_obj_t *ui_colon;
lv_obj_t *ui_weathershow;

ui_page_name_t ui_pages[7];

// SCREEN: ui_muyuplay
void ui_muyuplay_screen_init(void);
void ui_event_muyuplay(lv_event_t *e);
lv_obj_t *ui_muyuplay;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_muyu;
lv_obj_t *ui_gongdetxt;
lv_obj_t *ui_gongde_sum;
int gongde_sum = 0;

// SCREEN: ui_dice
void ui_dice_screen_init(void);
void ui_event_dice(lv_event_t *e);
lv_obj_t *ui_dice;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_shaizibut;
lv_obj_t *ui_shaizitxt;
lv_obj_t *ui_dice_canvas;

// SCREEN: ui_title
void ui_title_screen_init(void);
lv_obj_t *ui_title;
lv_obj_t *title_panel;
lv_obj_t *title_wifistate;
lv_obj_t *title_powerstate;
lv_obj_t *title_batterybor;
lv_obj_t *title_timestate;
lv_obj_t *title_batterytxt;

// SCREEN:ui_face
void ui_face_screen_init(void);
lv_obj_t *ui_face;
lv_obj_t *ui_Panel_face;
lv_obj_t *ui_face_canvas;
void ui_event_face(lv_event_t *e);
lv_obj_t *ui_img_face;

// SCREEN:ui_fish
void ui_fish_screen_init(void);
lv_obj_t *ui_fish;
lv_obj_t *ui_Panel_fish;
lv_obj_t *ui_fish_canvas;
void ui_event_fish(lv_event_t *e);

// SCREEN:ui_game_2048
void ui_game_screen_init(void);
lv_obj_t *ui_game;
lv_obj_t *ui_gamepanel;
lv_obj_t *ui_2048;
lv_obj_t *ui_score;
void ui_event_game(lv_event_t *e);
void ui_event_game_score(lv_event_t *e);

// SCREEN:ui_net
void ui_net_screen_init(void);
lv_obj_t *ui_net;
lv_obj_t *ui_netpanel;
void ui_event_net(lv_event_t *e);
char *url = ESP_SPARKBOT_URL;

// SCREEN:ui_mp3
void ui_mp3_screen_init(void);
lv_obj_t *ui_mp3;
lv_obj_t *ui_panel_mp3;
lv_obj_t *ui_mp3_title;
lv_obj_t *ui_mp3_progress;
lv_obj_t *ui_mp3_time;
lv_obj_t *ui_mp3_play_btn;
bool ui_mp3_is_playing = false;
static lv_timer_t *timer_mp3 = NULL;
void ui_event_mp3(lv_event_t *e);

void ui_event____initial_actions0(lv_event_t *e);
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void muyushow_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 150, 200);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_start(&PropertyAnimation_0);

}
void gonde_txt_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *opacity_anim_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    opacity_anim_user_data->target = TargetObject;

    lv_anim_t opacity_anim;
    lv_anim_init(&opacity_anim);
    lv_anim_set_time(&opacity_anim, 600);
    lv_anim_set_user_data(&opacity_anim, opacity_anim_user_data);
    lv_anim_set_custom_exec_cb(&opacity_anim, _ui_anim_callback_set_text_opacity);
    lv_anim_set_values(&opacity_anim, 255, 0);
    lv_anim_set_path_cb(&opacity_anim, lv_anim_path_linear);
    lv_anim_set_delay(&opacity_anim, delay);
    lv_anim_set_deleted_cb(&opacity_anim, _ui_anim_callback_free_user_data);
    lv_anim_start(&opacity_anim);

    ui_anim_user_data_t *position_anim_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    position_anim_user_data->target = TargetObject;

    lv_anim_t position_anim;
    lv_anim_init(&position_anim);
    lv_anim_set_time(&position_anim, 600);
    lv_anim_set_user_data(&position_anim, position_anim_user_data);
    lv_anim_set_custom_exec_cb(&position_anim, _ui_anim_callback_set_y);
    lv_anim_set_values(&position_anim, -70, -90);
    lv_anim_set_path_cb(&position_anim, lv_anim_path_linear);
    lv_anim_set_delay(&position_anim, delay);
    lv_anim_set_deleted_cb(&position_anim, _ui_anim_callback_free_user_data);
    lv_anim_start(&position_anim);
}

void blink_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 60);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void falldown_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -50, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_start(&PropertyAnimation_0);

}
void weather_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -200, -60);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_start(&PropertyAnimation_0);

}
void riseup_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_start(&PropertyAnimation_0);

}
void opaon_Animation(lv_obj_t *TargetObject, int delay)
{
    ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_text_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_home(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        riseup_Animation(ui_hour, 0);
        riseup_Animation(ui_min, 0);
        weather_Animation(ui_weathershow, 0);
        opaon_Animation(ui_weather, 0);
        opaon_Animation(ui_temp, 0);
        opaon_Animation(ui_weekday, 0);
        opaon_Animation(ui_date, 0);
        falldown_Animation(title_panel, 0);
        lv_obj_set_parent(title_panel, ui_Panel1);
        
        // 在进入home界面时播放echo1.wav
        extern void app_sr_play_echo1(void);
        app_sr_play_echo1();
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_muyuplay, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_muyuplay_screen_init);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_mp3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_mp3_screen_init);
    }
    if (event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_net, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_net_screen_init);
    }
}
void ui_event_muyuplay(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        ESP_LOGI(TAG, "### load muyu ###");
        lv_obj_set_parent(title_panel, ui_Panel3);
        gongde_sum = 0;
        lv_label_set_text_fmt(ui_gongde_sum, "#f1c40f 今日功德: %d#", gongde_sum);
        opaon_Animation(ui_gongde_sum, 0);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home_screen_init);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dice, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_dice_screen_init);
    }
    if (event_code == LV_EVENT_PRESSED) {
        static bool screen_change_next = false;
        gonde_txt_Animation(ui_gongdetxt, 0);
        gongde_sum = (gongde_sum < GONGDE_THRESHOLD) ?  gongde_sum + 1 : GONGDE_THRESHOLD;
        if (gongde_sum >= GONGDE_THRESHOLD && !screen_change_next) {
            muyushow_Animation(ui_muyu, 0);
            app_sr_paly_muyu();
            lv_label_set_text_fmt(ui_gongde_sum, "#f1c40f 功德圆满: %d#", gongde_sum);
            screen_change_next = true;
        } else if (gongde_sum >= GONGDE_THRESHOLD && screen_change_next) {
            _ui_screen_change(&ui_fish, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_fish_screen_init);
            lv_label_set_text_fmt(ui_gongde_sum, "#f1c40f 功德圆满: %d#", gongde_sum);

        } else {
            muyushow_Animation(ui_muyu, 0);
            lv_label_set_text_fmt(ui_gongde_sum, "#f1c40f 今日功德: %d#", gongde_sum);
            app_sr_paly_muyu();
        }
    }
}

// MP3播放器初始化函数
void ui_mp3_screen_init(void)
{
    // 创建基本容器
    ui_mp3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mp3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_mp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_panel_mp3 = lv_obj_create(ui_mp3);
    lv_obj_set_width(ui_panel_mp3, BSP_LCD_H_RES);
    lv_obj_set_height(ui_panel_mp3, 40);
    lv_obj_set_align(ui_panel_mp3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_panel_mp3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_panel_mp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panel_mp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panel_mp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建音乐标题标签
    ui_mp3_title = lv_label_create(ui_mp3);
    lv_obj_set_width(ui_mp3_title, BSP_LCD_H_RES - 20);
    lv_obj_set_style_text_align(ui_mp3_title, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(ui_mp3_title, LV_ALIGN_TOP_MID, 0, 50);
    lv_label_set_text(ui_mp3_title, "MP3 Player");
    lv_obj_set_style_text_font(ui_mp3_title, &lv_font_montserrat_14, 0);
    
    // 创建播放/暂停按钮
    ui_mp3_play_btn = lv_label_create(ui_mp3);
    lv_obj_set_width(ui_mp3_play_btn, 50);
    lv_obj_set_height(ui_mp3_play_btn, 50);
    lv_obj_align(ui_mp3_play_btn, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_text_font(ui_mp3_play_btn, &lv_font_montserrat_24, 0);
    lv_obj_set_style_text_align(ui_mp3_play_btn, LV_TEXT_ALIGN_CENTER, 0);
    lv_label_set_text(ui_mp3_play_btn, LV_SYMBOL_PLAY);
    
    // 创建进度条
    ui_mp3_progress = lv_bar_create(ui_mp3);
    lv_obj_set_width(ui_mp3_progress, BSP_LCD_H_RES - 40);
    lv_obj_set_height(ui_mp3_progress, 10);
    lv_obj_align(ui_mp3_progress, LV_ALIGN_BOTTOM_MID, 0, -50);
    lv_bar_set_value(ui_mp3_progress, 0, LV_ANIM_OFF);
    
    // 创建时间显示
    ui_mp3_time = lv_label_create(ui_mp3);
    lv_obj_set_width(ui_mp3_time, BSP_LCD_H_RES - 40);
    lv_obj_align(ui_mp3_time, LV_ALIGN_BOTTOM_MID, 0, -20);
    lv_obj_set_style_text_align(ui_mp3_time, LV_TEXT_ALIGN_CENTER, 0);
    lv_label_set_text(ui_mp3_time, "0:00 / 0:00");
    
    // 添加事件处理
    lv_obj_add_event_cb(ui_mp3, ui_event_mp3, LV_EVENT_ALL, NULL);
    
    ESP_LOGI(TAG, "MP3 player UI initialized");
}

static void fish_lottie_timer_player_cb(lv_timer_t *tmr)
{
    static int position_x = FISH_X_START;

    if ((int)lv_lottie_get_start_f(ui_fish_canvas) > 35 &&  position_x <= FISH_X_START) {
        lv_lottie_set_segment(ui_fish_canvas, 1, 36 - 1, true);
        ESP_LOGI(TAG, "reset fish");
    }

    if ((int)lv_lottie_get_start_f(ui_fish_canvas) > 35) {
        position_x = (position_x < FISH_X_END) ? position_x + 5 : FISH_X_START;
        // ESP_LOGI(TAG, "position_x: %d", position_x);
        lv_obj_set_x(ui_fish_canvas, position_x);
    } else {
        position_x = (position_x < FISH_X_END) ? position_x + 2 : FISH_X_START;
        // ESP_LOGI(TAG, "position_x: %d", position_x);
        lv_obj_set_x(ui_fish_canvas, position_x);
    }
}

void ui_event_dice(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        lv_obj_set_parent(title_panel, ui_Panel4);
    }

    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
    }

    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_muyuplay, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_muyuplay_screen_init);
    }
}

void ui_event_face(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {

        const void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
    }

    if (event_code == LV_EVENT_FACE_LOOK) {
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
        lv_lottie_set_segment(ui_face_canvas, 0, 58, false);
    }

    if (event_code == LV_EVENT_FACE_ASK) {
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_ASK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_ASK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
        lv_lottie_set_segment(ui_face_canvas, 1, 45, false);
    }

    if (event_code == LV_EVENT_FACE_THINK) {
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_THINK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_THINK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
        lv_lottie_set_segment(ui_face_canvas, 1, 30, true);
    }

    if (event_code == LV_EVENT_FACE_SPEAK) {
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_SPEAK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_SPEAK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
        lv_lottie_set_segment(ui_face_canvas, 5, 17, true);
    }


    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {

        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_game, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_game_screen_init);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {

        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dice, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_dice_screen_init);
    }
}

void ui_event_fish(lv_event_t *e)
{
    static uint16_t default_width = LOTTIE_SIZE_HOR_MIN;
    static uint16_t default_height = LOTTIE_SIZE_VER_MIN;

    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *user_data = lv_event_get_user_data(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        lv_obj_set_parent(title_panel, ui_fish);

        const void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_FISH_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_FISH_JSON);
        lv_lottie_set_src_data(ui_fish_canvas, data, size);
        lv_lottie_set_segment(ui_fish_canvas, 1, 36 - 1, true);

        lv_anim_t *anmi = lv_lottie_get_anim(ui_fish_canvas);
        timer_fish = lv_timer_create(fish_lottie_timer_player_cb, 10, NULL);
    }
    if (event_code == LV_EVENT_PRESSED) {
        default_width *= 1.1;
        default_height *= 1.1;
        if (default_width >= LOTTIE_SIZE_HOR || default_height > LOTTIE_SIZE_VER) {
            default_width = LOTTIE_SIZE_HOR_MIN;
            default_height = LOTTIE_SIZE_VER_MIN;
        }

        ESP_LOGI(TAG, "Resize Fish:[%d, %d]", default_width, default_height);
        lv_lottie_resize(ui_fish_canvas, default_width, default_height);
        lv_lottie_set_segment(ui_fish_canvas, 40, 96 - 1, false);
    }

    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {

        lv_timer_del(timer_fish);
        timer_fish = NULL;

        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dice, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_dice_screen_init);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {

        lv_timer_del(timer_fish);
        timer_fish = NULL;

        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_dice, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_dice_screen_init);
    }
}

void ui_event_game(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *game_handle = lv_event_get_user_data(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        ESP_LOGI(TAG, "### Load Game ###");
        lv_obj_set_parent(title_panel, ui_game);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_mp3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home_screen_init);
    }
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
    }
    if (event_code == LV_EVENT_PRESSED) {
        lv_100ask_2048_set_new_game(game_handle);
    }
}

void ui_event_game_score(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *label = lv_event_get_user_data(e);

    if (event_code == LV_EVENT_VALUE_CHANGED) {
        if (lv_100ask_2048_get_best_tile(target) >= 2048) {
            lv_label_set_text(label, "#00b329 YOU WIN! #");
        } else if (lv_100ask_2048_get_status(target)) {
            lv_label_set_text(label, "#ff0000 GAME OVER! #");
        } else {
            lv_label_set_text_fmt(label, "#FFFFFF SCORE:# #FF0000 %d#", lv_100ask_2048_get_score(target));
        }
    }
}

void ui_event_net(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        ESP_LOGI(TAG, "### Load qrcode ###");
        lv_obj_set_parent(title_panel, ui_net);
    }
    if (event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home_screen_init);
    }
}

#include "app_mp3_player.h"

// MP3播放器的定时器回调函数
static void mp3_timer_cb(lv_timer_t *tmr)
{
    // 从MP3播放器获取当前进度
    int progress = app_mp3_player_get_progress();
    
    // 更新进度条
    lv_bar_set_value(ui_mp3_progress, progress, LV_ANIM_ON);
    
    // 获取当前位置和总时长
    int curr_sec = app_mp3_player_get_position();
    int total_sec = app_mp3_player_get_duration();
    
    int curr_min = curr_sec / 60;
    curr_sec = curr_sec % 60;
    
    int total_min = total_sec / 60;
    int total_sec_remainder = total_sec % 60;
    
    static char time_txt[32];
    snprintf(time_txt, sizeof(time_txt), "%d:%02d / %d:%02d", 
             curr_min, curr_sec, total_min, total_sec_remainder);
    lv_label_set_text(ui_mp3_time, time_txt);
    
    // 根据播放状态更新播放/暂停按钮
    if (app_mp3_player_is_playing()) {
        lv_label_set_text(ui_mp3_play_btn, LV_SYMBOL_PAUSE);
    } else {
        lv_label_set_text(ui_mp3_play_btn, LV_SYMBOL_PLAY);
    }
}

void ui_event_mp3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        ESP_LOGI(TAG, "### Load MP3 player ###");
        lv_obj_set_parent(title_panel, ui_panel_mp3);
        timer_mp3 = lv_timer_create(mp3_timer_cb, 1000, NULL);  // 每秒更新一次
        
        // 设置初始歌曲标题
        lv_label_set_text(ui_mp3_title, "Demo Song - ESP32 Player");
    }

    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) ||
            (event_code == LV_EVENT_SCREEN_NEXT)) {

        if (timer_mp3) {
            lv_timer_del(timer_mp3);
            timer_mp3 = NULL;
        }

        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home_screen_init);
    }
    
    if ((event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) ||
            (event_code == LV_EVENT_SCREEN_PRIVIOUS)) {

        if (timer_mp3) {
            lv_timer_del(timer_mp3);
            timer_mp3 = NULL;
        }

        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_game, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_game_screen_init);
    }
    
    // 按钮1短按 - 播放/暂停
    if (event_code == LV_EVENT_PRESSED) {
        ui_mp3_is_playing = !ui_mp3_is_playing;
        
        if (ui_mp3_is_playing) {
            ESP_LOGI(TAG, "begin play");// 播放音乐
            app_mp3_player_play("jntm.wav");

            lv_label_set_text(ui_mp3_play_btn, LV_SYMBOL_PAUSE);
            // 实际调用播放MP3函数
        } else {
            // 暂停音乐
            ESP_LOGI(TAG, "pause play");
            app_mp3_player_pause();
            lv_label_set_text(ui_mp3_play_btn, LV_SYMBOL_PLAY);
            // 实际调用暂停MP3函数
        }
    }
}

void ui_event____initial_actions0(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {
        blink_Animation(ui_colon, 0);
    }
}

///////////////////// SCREENS ////////////////////

typedef struct {
    lv_obj_t *obj;
    lv_event_code_t event_code;
    void *user_data;
    void *param;
} lv_sys_event_t;

static QueueHandle_t ui_sys_event = NULL;

void ui_system_update(lv_timer_t *timer)
{
    lv_sys_event_t event;
    if (pdPASS == xQueueReceive(ui_sys_event, &event, 0)) {
        lv_event_send(event.obj, event.event_code, event.user_data);
    }
}

void ui_send_sys_event(lv_obj_t *obj, lv_event_code_t event_code, void *user_data)
{
    lv_sys_event_t eventOut;

    eventOut.obj = obj;
    eventOut.event_code = event_code;
    eventOut.user_data = user_data;

    xQueueSend(ui_sys_event, &eventOut, 0);

    return;
}

void ui_init(void)
{

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_title_screen_init();
    ui_home_screen_init();
    ui_muyuplay_screen_init();
    ui_dice_screen_init();
    ui_face_screen_init();
    ui_fish_screen_init();
    ui_game_screen_init();
    ui_net_screen_init();
    ui_mp3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    ui_pages[0].page = ui_home;
    ui_pages[0].name = "home";

    ui_pages[1].page = ui_muyuplay;
    ui_pages[1].name = "muyu";

    ui_pages[2].page = ui_dice;
    ui_pages[2].name = "dice";

    ui_pages[3].page = ui_face;
    ui_pages[3].name = "face";

    ui_pages[4].page = ui_fish;
    ui_pages[4].name = "fish";

    ui_pages[5].page = ui_2048;
    ui_pages[5].name = "2048";

    ui_pages[6].page = ui_mp3;
    ui_pages[6].name = "mp3player";

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_home);

    ui_sys_event = xQueueCreate(4, sizeof(lv_sys_event_t));
    ESP_ERROR_CHECK_WITHOUT_ABORT((ui_sys_event) ? ESP_OK : ESP_FAIL);

    lv_timer_create(ui_system_update, 10,  NULL);
}
